### ISSUE TITLE
requirements-dev.txt vs requirements.txt

### ISSUE THREAD

**Issue by edwardcjohnson** [duarteocarmo/boilerplate#4]
Based on the separation of dependencies and dev-dependencies inside your `pyproject.toml`, I would have expected the output from pip-compile (relevant snippet from your `makefile` shown below) to be different in `requirements-dev.txt` vs `requirements.txt`, however the two files are identical. For example, since "black" is listed as a "dev" dependency in your `pyproject.toml`, i would expect to see it in the generated `requirements-dev.txt`. 

I think you need an additional argument in your pip-compile e.g. `--extra=dev`, so the complete line for the dev requirements would be:
`pip-compile --resolver=backtracking --extra=dev --output-file=requirements-dev.txt pyproject.toml`

```
## Build using pip-tools
build:
	python -m pip install --upgrade pip
	python -m pip install pip-tools
	pip-compile --resolver=backtracking --output-file=requirements.txt pyproject.toml
	pip-compile --resolver=backtracking --output-file=requirements-dev.txt pyproject.toml
```

**Comment by duarteocarmo** [comment]
@edwardcjohnson  - I noticed this exact same thing a couple of months ago. Forgot updating here. We def. need the `--extra-dev` for the dev!

Updated!

```
## Build using pip-tools
build:
	python -m pip install --upgrade pip
	python -m pip install pip-tools
	pip-compile --resolver=backtracking --output-file=requirements.txt pyproject.toml
	pip-compile --extra=dev --resolver=backtracking --output-file=requirements-dev.txt pyproject.toml
```

**Comment by edwardcjohnson** [comment]
Great!
Also, I greatly enjoy your blog. So thank you for that!

**Comment by duarteocarmo** [comment]
Appreciate the kind words @edwardcjohnson!
